<?php

require_once dirname(__FILE__) . '/tocctiles.admin.inc';
require_once dirname(__FILE__) . '/tocctiles.block.inc';
require_once dirname(__FILE__) . '/tocctiles.taxonomy.inc';

/**
 * Implements hook_menu()
 * 
 * @return array
 */
function tocctiles_menu()
{   
    $items['admin/config/tocc/tocctiles'] = array(
        'title' => t('TOCC Tiles'),
        'description' => t('Configuration for the module containing the block of image Tiles'),
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );
            
    $items['admin/config/tocc/tocctiles/settings'] = array(
        'title' => t('TOCC Tiles'),
        'description' => t('Configuration for the module containing the block of image Tiles'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('tocctiles_config_form'),
        'access arguments' => array('access administration pages tocctiles'),
        'type' => MENU_LOCAL_TASK,
        'file' => 'tocctiles_admin.inc',
    );
            
    return $items;
}

/**
 * Implements hook_permission()
 * 
 * @return array
 */
function tocctiles_permission()
{
    return array(
        'administer tocctiles' => array(
            'title' => t('Manage the TOCC Tiles module'),
            'description' => t('Allows users to configure the TOCC Tiles module'),
        )
    );
}

/**
 * Implements hook_theme()
 */
function tocctiles_theme($existing, $type, $theme, $path)
{
    return array(
        'tocctiles_block' => array(
            'variables' => array(
                'content' => NULL,
                'tiles' => NULL
            ),
            'template' => 'templates/tocctiles.block'
        ),
        'tocctile' => array(
            'variables' => array(
                'image' => NULL,
                'title' => NULL,
                'description' => NULL,
                'buttontext' => NULL,
                'link' => NULL
            ),
            'template' => 'templates/tocctile'
        )
    );
}